MRI_TOKENS = '①' * 32

INSTRUCTION_LIST = [
    "Describe the image in a detailed and informative manner.",
    "Summarize the visual content of the image clearly.",
    "Provide a rich, descriptive narrative of the image.",
    "Offer a brief but comprehensive description of the image.",
    "Analyze the image thoroughly and in detail.",
    "Narrate the contents of the image with precision.",
    "Give a detailed account of the given image.",
    "Describe the following image in detail.",
    "Examine the image closely and share its details.",
    "Give a short, clear explanation of the image.",
    "Break down the elements of the image in detail.",
    "Relay a brief, clear account of the image shown.",
    "Share a concise interpretation of the image provided.",
    "Write a short but informative summary of the image.",
    "Walk through the important details of the image.",
    "Explain the various aspects of the image.",
    "Describe the image concisely.",
    "Offer a succinct explanation of the image.",
    "Characterize the image with a well-detailed description.",
    "Write an exhaustive depiction of the given image.",
    "Clarify the contents of the displayed image in great detail.",
    "Render a clear and concise summary of the image.",
    "Give an elaborate explanation of the image you see.",
    "Offer a thorough analysis of the image.",
    "Share a comprehensive rundown of the presented image.",
    "Create a compact narrative representing the image.",
    "Present a concise description of the image’s key features.",

    "Can you provide a radiology report for this medical image?",
    "Describe the medical image you see.",
    "What is depicted in this picture?",
    "Please report this medical scan.",
    "What is the medical significance of this image?",
    "What can you infer from this picture?",
    "Can you provide a quick summary of this image?",
    "Describe this medical scan.",
    "Please write a radiology report for this image.",
    "Can you summarize the images presented?",
    "Please generate a radiology report for this scan.",
    "Describe the regions of interest in this scan.",
    "Please provide a caption for this medical image.",
    "Can you provide a brief summary of this radiograph?",
    "Describe the structures involved in this medical image.",
    "What are the findings presented in this medical scan?",
    "Please write a radiology report for this scan.",
    "Can you provide a description of this medical scan?",
    "Please caption this medical scan.",
    "Can you provide a report summary for this medical scan?",

    "Please describe this picture.",
    "Can you describe the image for me?",
    "What details stand out in this image?",
    "Could you provide a detailed description of what is shown in the picture?",
    "What is the main focus of this photograph?",
    "Describe the composition and the subjects in this picture.",
    "Explain the visual content of the image.",
    "Analyze the image in a comprehensive and detailed manner.",
    "Write a detailed description of the given image.",
    "What is this photo about?",
    "What is depicted in the image?",
]

INSTRUCTION_CASE_LIST = [
    "Can you provide a case report?",
    "Please write a case report.",
    "Please generate a case report.",
    "Can you provide a case summary?",
]
